In [1]:
from collections import abc

issubclass(tuple, abc.Sequence)

True

In [2]:
issubclass(list, abc.MutableSequence)

True

## List Comprehensions and Readability

In [3]:
symbols = '$¢£¥€¤'

In [4]:
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
codes

[36, 162, 163, 165, 8364, 164]

In [5]:
# list comprehensive
codes = [ord(symbol) for symbol in symbols]
codes

[36, 162, 163, 165, 8364, 164]

## Local Scope within comprehensions and generator expressions

In [6]:
x = 'ABC'
codes = [ord(x) for x in x]
print(x)
print(codes)

ABC
[65, 66, 67]


In [7]:
codes = [last := ord(c) for c in x]
print(last)
print(c)

67


NameError: name 'c' is not defined

## Listcomps Versus map and filter

In [8]:
symbols = '$¢£¥€¤'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
beyond_ascii

[162, 163, 165, 8364, 164]

In [9]:
beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))
beyond_ascii

[162, 163, 165, 8364, 164]

## Cartesian Products

In [10]:
colors = ['balck', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]
tshirts

[('balck', 'S'),
 ('balck', 'M'),
 ('balck', 'L'),
 ('white', 'S'),
 ('white', 'M'),
 ('white', 'L')]

In [11]:
for color in colors:
    for size in sizes:
        print((color, size))

('balck', 'S')
('balck', 'M')
('balck', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [12]:
tshirts = [(color, size) for size in sizes
                         for color in colors]
tshirts

[('balck', 'S'),
 ('white', 'S'),
 ('balck', 'M'),
 ('white', 'M'),
 ('balck', 'L'),
 ('white', 'L')]

In [14]:
#cards = [Card(rank, suit) for suit in suits
#                          for rank in ranks]

## Generator Expressions

In [15]:
symbols = '$¢£¥€¤'
tuple(ord(symbol) for symbol in symbols)

(36, 162, 163, 165, 8364, 164)

In [16]:
import array
array.array('I', (ord(symbol) for symbol in symbols))


array('I', [36, 162, 163, 165, 8364, 164])

In [18]:
## Cartesian product in a generator expression
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirt in (f'{c} {s}' for s in sizes for c in colors):
    print(tshirt)

black S
white S
black M
white M
black L
white L


# Tuple

## Tuples are not just immutable Lists

### Tuples as Records

In [20]:
## Tuples used as records
lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32_450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]
for passport in sorted(traveler_ids):
    print('%s/%s' % passport)

BRA/CE342567
ESP/XDA205856
USA/31195855


In [21]:
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


## Tuples as immutable Lists

In [1]:
a = (10, 'alpha', [1, 2])
b = (10, 'alpha', [1, 2])
a == b

True

In [2]:
b[-1].append(99)
a == b

False

In [3]:
def fixed(o):
    try:
        hash(0)
    except TypeError:
        return False
    return True

In [4]:
tf = (10, 'alpha', (1, 2))
tm = (10, 'alpha', [1, 2])

In [5]:
fixed(tf)

True

In [6]:
fixed(tm)

True

## Unpacking Sequences and Iterables

In [7]:
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates
print(latitude)
print(longitude)

33.9425
-118.408056


In [8]:
divmod(20, 8)

(2, 4)

In [9]:
t = (20, 8)

In [10]:
divmod(*t)

(2, 4)

In [11]:
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [12]:
import os
_, filename = os.path.split('/home/luciano/.ssh/id_rsa.pub')
filename

'id_rsa.pub'

In [13]:
a, b, *rest = range(5)
a, b, rest

(0, 1, [2, 3, 4])

In [14]:
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [15]:
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [16]:
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [18]:
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [19]:
def fun(a, b, c, d, *rest):
    return a, b, c, d, rest

In [20]:
fun(*[1, 2], 3, *range(4, 7))

(1, 2, 3, 4, (5, 6))

In [22]:
*range(4), 4

(0, 1, 2, 3, 4)

In [23]:
[*range(4), 4]

[0, 1, 2, 3, 4]

In [24]:
{*range(4), 4, *(5, 6, 7)}

{0, 1, 2, 3, 4, 5, 6, 7}

### Nested unpacking

In [1]:
metro_ares = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('São Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

In [27]:
def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
    for name, _, _, (lat, lon) in metro_ares:
        if lon <= 0:
            print(f'{name:15} | {lat:9.4f} {lon:9.4f}')

if __name__ == '__main__':
    main()

                |  latitude | longitude
Mexico City     |   19.4333  -99.1333
New York-Newark |   40.8086  -74.0204
São Paulo       |  -23.5478  -46.6358


### Pattern Matching with Sequences

In [28]:
def handle_command(self, message):
    match message:
        case ['BEEPER', frequency, times]:
            self.beep(times, frequency)
        case ['NECK', angle]:
            self.rotate_neck(angle)
        case ['LED', ident, intensity]:
            self.leds[ident].set_brightness(ident, intensity)
        case ['LED', ident, red, green, blue]:
            self.leds[ident].set_color(ident, red, green, blue)
        case _:
            raise InvalidCommand(message)

In [2]:
def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
    for record in metro_ares:
        match record:
            case [name, _, _, (lat, lon)] if lon <= 0:
                print(f'{name:15} | {lat:9.4f} | {lon:9.4f}')

In [3]:
def main():
    print(f'{"":15} | {"latitude":>9} | {"longitude":>9}')
    for record in metro_ares:
        match record:
            case [name, _, _, (lat, lon) as coord] if lon <= 0:
                print(f'{name:15} | {lat:9.4f} | {lon:9.4f}')

### Pattern Matching Sequences in an Interpreter

In [ ]:
parse

### Slicing

In [1]:
l = [10, 20, 30, 40, 50, 60]
print(l[:3])
print(l[3:])

[10, 20, 30]
[40, 50, 60]


In [2]:
invoice = """
0.....6.................................40........52...55........
1909 Pimoroni PiBrella                      $17.50    3    $52.50
1489 6mm Tactile Switch x20                  $4.95    2     $9.90
1510 Panavise Jr. - PV-201                  $28.00    1    $28.00
1601 PiTFT Mini Kit 320x240                 $34.95    1    $34.95
"""

In [3]:
SKU = slice(0, 6)

In [4]:
DESCRIPTION = slice(6, 40)
UNIT_PRICE = slice(40, 52)
QUANTITY = slice(52, 55)
ITEM_TOTAL = slice(55, None)
line_items = invoice.split('\n')[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

    $17.50   imoroni PiBrella                  
     $4.95   mm Tactile Switch x20             
    $28.00   anavise Jr. - PV-201              
    $34.95   iTFT Mini Kit 320x240             
 


## Assigning to Slices

In [1]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
l[2:5] = [20, 30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [3]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [4]:
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [5]:
5 * 'abcd'

'abcdabcdabcdabcdabcd'

## Building Lists of Lists

In [6]:
boards = [['_'] * 3 for i in range(3)]
boards

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [7]:
boards[1][2] = 'X'
boards

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [8]:
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [9]:
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [10]:
board = []
for i in range(3):
    row = ['_'] * 3
    board.append(row)
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [11]:
board[2][0] = 'X'
board

[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

In [12]:
l = [1, 2, 3]
id(l)

140198066109056

In [13]:
l *= 2
id(l)

140198066109056

In [14]:
t = (1, 2, 3)
id(t)

140198065143424

In [15]:
t *= 2
id(t)

140198064658688

In [16]:
t = (1, 2, [30, 40])
t[2] += [50, 60]

TypeError: 'tuple' object does not support item assignment

In [17]:
t

(1, 2, [30, 40, 50, 60])

In [18]:
## Bytecode for the expression s[a] += b
dis.dis('s[a] += b')

NameError: name 'dis' is not defined

### list.sort Versus the sorted Built-In

In [1]:
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [2]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [3]:
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [4]:
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [5]:
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [6]:
fruits

['grape', 'raspberry', 'apple', 'banana']

In [7]:
fruits.sort()

In [8]:
fruits

['apple', 'banana', 'grape', 'raspberry']

### Managing Ordered Sequences with Bisect

In [9]:
import bisect
import sys

In [10]:
HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}      {2}{0:<2d}'

In [11]:
def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '   |'
        print(ROW_FMT.format(needle, position, offset))

if __name__ == '__main__':

    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect

    print('DEMO:', bisect_fn__name__)
    print('hastack ->', ' '.join(f'{n:2}' for n in HAYSTACK))
    demo(bisect_fn)

NameError: name 'bisect_fn__name__' is not defined

## Arrays

In [12]:
from array import array
from random import random

floats = array('d', (random() for i in range(10**7)))
floats[-1]

0.7183072014466895

In [15]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)

In [16]:
fp.close()
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
floats2[-1]

0.7183072014466895

In [17]:
floats2 == floats

True

### Memory Views

In [18]:
from array import array
octets = array('B', range(6))
m1 = memoryview(octets)
m1.tolist()

[0, 1, 2, 3, 4, 5]

In [19]:
m2 = m1.cast('B', [2, 3])
m2.tolist()

[[0, 1, 2], [3, 4, 5]]

In [20]:
m3 = m1.cast('B', [3, 2])
m3.tolist()

[[0, 1], [2, 3], [4, 5]]

In [21]:
m2[1, 1] = 22
m3[1, 1] = 33
octets

array('B', [0, 1, 2, 33, 22, 5])

In [29]:
import array
numbers = array.array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
len(memv)

5

In [30]:
memv[0]

-2

In [31]:
memv_oct = memv.cast('B')
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [32]:
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

### Numpy

In [33]:
import numpy as np
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
type(a)

numpy.ndarray

In [35]:
a.shape

(12,)

In [36]:
a.shape = 3, 4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
a[2]

array([ 8,  9, 10, 11])

In [38]:
a[2, 1]

9

In [39]:
a[:, 1]

array([1, 5, 9])

In [40]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [42]:
# import numpy

# floats = numpy.loadtxt('floats-10M-lines.txt')
# floats[-3:]

### Deques and Other Queues

In [43]:
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [44]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [45]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)

In [46]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)